#!/usr/bin/env python3
"""Render Formula/cm.rb from a release's downloaded .sha256 sidecars."""

from __future__ import annotations

import argparse
import pathlib
import re

OFFERED = {
    "aarch64-apple-darwin": ("macos", "arm"),
    "aarch64-unknown-linux-musl": ("linux", "arm"),
    "x86_64-unknown-linux-musl": ("linux", "intel"),
}

TEMPLATE = '''# Generated by .github/scripts/render-homebrew-formula.py in
# https://github.com/{repository} from release {tag}. Edit the generator, not this file.
class Cm < Formula
  desc "Campaign manager: the campaign lifecycle as one tool"
  homepage "https://github.com/{repository}"
  license any_of: ["Apache-2.0", "MIT"]

{platforms}
  def install
    bin.install "cm"
    doc.install "README.md", "LICENSE-APACHE", "LICENSE-MIT"
  end

  test do
    assert_match "cm #{{version}}", shell_output("#{{bin}}/cm --version")
  end
end
'''


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repository", default="dekopon-agents/cm")
    parser.add_argument("--tag", required=True)
    parser.add_argument("--checksums", required=True, type=pathlib.Path)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    arguments = parser.parse_args()

    if not re.fullmatch(r"v\d+\.\d+\.\d+", arguments.tag):
        raise SystemExit(f"{arguments.tag} is not a v<major>.<minor>.<patch> tag")
    version = arguments.tag[1:]
    pattern = re.compile(rf"^cm-{re.escape(version)}-(?P<target>.+)\.tar\.gz\.sha256$")

    by_os: dict[str, dict[str, tuple[str, str]]] = {}
    for sidecar in sorted(arguments.checksums.iterdir()):
        match = pattern.match(sidecar.name)
        if not match:
            continue
        target = match.group("target")
        if target not in OFFERED:
            raise SystemExit(f"release publishes {target}, which OFFERED does not place")
        checksum, named = sidecar.read_text(encoding="utf-8").split()
        archive = sidecar.name.removesuffix(".sha256")
        if not re.fullmatch(r"[0-9a-f]{64}", checksum) or pathlib.PurePath(named).name != archive:
            raise SystemExit(f"{sidecar.name}: malformed sidecar")
        url = f"https://github.com/{arguments.repository}/releases/download/{arguments.tag}/{archive}"
        operating_system, architecture = OFFERED[target]
        by_os.setdefault(operating_system, {})[architecture] = (url, checksum)
    missing = sorted(set(OFFERED) - {
        target for target, (system, arch) in OFFERED.items() if arch in by_os.get(system, {})
    })
    if missing:
        raise SystemExit(f"release {arguments.tag} has no checksum for {', '.join(missing)}")

    lines: list[str] = []
    for operating_system in ("macos", "linux"):
        architectures = by_os[operating_system]
        lines.append(f"  on_{operating_system} do")
        blocks = []
        for architecture in ("arm", "intel"):
            if architecture in architectures:
                url, checksum = architectures[architecture]
                blocks.append(
                    f'    on_{architecture} do\n      url "{url}"\n      sha256 "{checksum}"\n    end'
                )
        lines.append("\n\n".join(blocks))
        lines.append("  end")
        lines.append("")

    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(
        TEMPLATE.format(
            repository=arguments.repository, tag=arguments.tag, platforms="\n".join(lines)
        ),
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
